
export const meals = [
    {
      id: 1,
      category: "Sweet",
      name: "Pancake",
      calories: 500,
      carbs: 223,
      protein: 200,
      fat: 10,
      meal: "breakfast",
    },
    {
      id: 2,
      category: "Grain",
      name: "Pasta",
      calories: 500,
      carbs: 223,
      protein: 200,
      fat: 10,
      meal: "lunch",
    },
    {
      id: 3,
      category: "Meat",
      name: "Steak",
      calories: 500,
      carbs: 223,
      protein: 200,
      fat: 10,
      meal: "dinner",
    },
    {
      id: 4,
      category: "Meat",
      name: "Salmon",
      calories: 500,
      carbs: 223,
      protein: 200,
      fat: 10,
      meal: "dinner",
    },
  ];